# Generated by Django 2.1.3 on 2018-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
            ],
        ),
    ]
