# Generated by Django 2.1.3 on 2018-11-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriaIMDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='categorias',
            new_name='categories',
        ),
    ]
